// WHAT: Shared car inventory data for all pages.
// EDIT THIS: Change prices, specs, images here — every page updates automatically.

export type Car = {
  id: number;
  name: string;
  make: string;
  model: string;
  year: number;
  price: number;
  body: string;
  color: string;
  mileage: string;
  mpg: string;
  image: string;
  images: string[];
  badge: string;
  trim: string;
  engine: string;
  transmission: string;
  drivetrain: string;
  seats: number;
  description: string;
  features: string[];
};

export const allCars: Car[] = [

  // ── BMW ────────────────────────────────────────────────────────────────────
 {
  id: 1,
  name: "M760i xDrive",
  make: "BMW",
  model: "7 Series M-Performance",
  year: 2024,
  price: 700000,
  body: "Sedan",
  color: "Frozen Deep Grey",
  mileage: "New",
  mpg: "Petrol",
  image: "/bmw/m7/f.jpg",
  images: [
    "/bmw/m7/f.jpg",
    "/bmw/m7/s.jpg",
    "/bmw/m7/i.jpg",
    "/bmw/m7/r.jpg"
  ],
  badge: "M Performance",
  trim: "M760i xDrive",
  engine: "4.4L BMW M TwinPower Turbo V8",
  transmission: "8-Speed Sport Automatic",
  drivetrain: "AWD",
  seats: 5,
  description: "The BMW M760i combines the ultimate executive luxury of the 7 Series with the heart-pounding performance of BMW M.",
  features: [
    "Executive Lounge Seating",
    "M Sport Differential",
    "Panoramic Sky Lounge LED Roof",
    "Iconic Glow Kidney Grille"
  ]
},
{
  id: 2,
  name: "M8 Coupe",
  make: "BMW",
  model: "8 Series M",
  year: 2024,
  price: 600000,
  body: "Sedan / Coupe",
  color: "Red",
  mileage: "New",
  mpg: "Petrol",
  image: "/bmw/m8/f.jpg",
  images: [
  "/bmw/m8/f.jpg",
  "/bmw/m8/s.jpg",
  "/bmw/m8/i.jpg",
  "/bmw/m8/r.jpg",
  ],
  badge: "Competition",
  trim: "M8 Competition",
  engine: "4.4L V8 BMW M TwinPower Turbo",
  transmission: "8-Speed M Steptronic",
  drivetrain: "M xDrive (AWD)",
  seats: 5,
  description: "The M8 Gran Coupe is a four-door masterpiece, blending world-class luxury with 617 horsepower of pure M performance.",
  features: [
    "Carbon Fiber Roof",
    "M Track Mode",
    "Adaptive M Suspension",
    "Harman Kardon Surround Sound"
  ]
},
{
  id: 3,
  name: "BMW XM",
  make: "BMW",
  model: "XM",
  year: 2024,
  price: 1000000,
  body: "SUV",
  color: "Metalic Blue",
  mileage: "New",
  mpg: "46 MPGe / 14 city / 20 hwy",
  image: "/bmw/xm/f.jpg",
  images: [
    "/bmw/xm/f.jpg",
    "/bmw/xm/s.jpg",
    "/bmw/xm/i.jpg",
    "/bmw/xm/r.jpg",
  ],
  badge: "M Hybrid",
  trim: "XM Label Red Ready",
  engine: "4.4L V8 BMW M TwinPower Turbo with Electric Motor",
  transmission: "8-Speed M Steptronic",
  drivetrain: "M xDrive (AWD)",
  seats: 5,
  description: "The first-ever BMW XM combines high-performance M power with cutting-edge plug-in hybrid technology in a bold SUV design.",
  features: [
    "M Lounge Interior",
    "3D Sculptural Prism Headliner",
    "Active Roll Stabilization",
    "Ambient Lighting with M Colors"
  ]
},

  // ── MASERATI ───────────────────────────────────────────────────────────────
  {
    id: 4,
    name: " Levante Trofeo",
    make: "Maserati",
    model: "Levante Trofeo",
    year: 2024,
    price: 125000,
    body: "SUV",
    color: "Red",
    mileage: "New",
    mpg: "Gasoline",
    image: "/maserati/maserati_levante_trofeo_dynamic_18.jpg",
    images: [
      "/maserati/image (26).jpg",
      "/maserati/image (27).jpg",
      "/maserati/image (24).jpg",
      "/maserati/image (25).jpg",
    ],
    badge: "Trofeo ",
    trim: "Trofeo ",
    engine: "3.8-liter Twin-Turbo V8",
    transmission: "8-speed ZF automatic",
    drivetrain: "AWD",
    seats: 5,
    description: "As the high-performance pinnacle of Maserati's SUV lineup, the Levante Trofeo is powered by a Ferrari-assembled twin-turbo V8. It perfectly blends supercar dynamics with everyday utility, offering an aggressive carbon-fiber exterior and a handcrafted 'Pieno Fiore' leather cabin for ultimate Italian luxury.",
    features: ["Ferrari-Built 3.8L V8 Engine", "Corsa Driving Mode with Launch Control", "Pieno Fiore Natural Leather Interior", "17-Speaker Bowers & Wilkins Audio", "22-inch Forged Orione Wheels", " Maserati Intelligent Assistant (MIA)", "Active Air Suspension System", "Unique VIN Plaque"],
  },
  {
    id: 5,
    name: "Maserati Grecale Cristallo",
    make: "Maserati",
    model: "Grecale Cristallo",
    year: 2026,
    price: 98000,
    body: "Luxury Compact SUV",
    color: "Icy Pearl Blue",
    mileage: "New",
    mpg: "25 Combined MPG (9.4 L/100km)",
    image: "/maserati/2025-maserati-grecale-trofeo-blu-intenso-pr-135-6762ca385f599.JBG.avif",
    images: [
      "/maserati/image (29).jpg",
      "/maserati/image (30).jpg",
      "/maserati/image (28).jpg",
      "/maserati/image (31).jpg",
    ],
    badge: "Best Seller",
    trim: "Premium Luxury Platinum",
    engine: "2.0L Turbocharged L4",
    transmission: "8-Speed Automatic",
    drivetrain: "4WD",
    seats: 5,
    description: "The 2026 Maserati Grecale Cristallo is a rare 'Fuoriserie' masterpiece, finished in the exclusive Azzurro Aureo paint inspired by the snowy Alps. This Modena-based edition features a 325hp mild-hybrid engine, ice-white leather interiors, and 21-inch CRIO wheels, celebrating the peak of Italian luxury and alpine elegance.",  
    features: ["Exclusive Azzurro Aureo Paint", "2.0L Turbo Mild-Hybrid Engine", "21-inch CRIO Diamond-Cut Wheels", "Ice-White Premium Leather Interior", "Sonus faber 14-Speaker Audio", "Adaptive Air Suspension", "Milano-Cortina 2026 Special Edition"],  
  },
    

    // ── CADILLAC ───────────────────────────────────────────────────────────────
  {
    id: 6,
    name: "CT6 Premium Luxury",
    make: "Cadillac",
    model: "CT6",
    year: 2026,
    price: 68000,
    body: "Sedan",
    color: " Midnight Sky Metallic",
    mileage: "new",
    mpg: "21 city / 29 hwy",
    image: "/Cadillac/2024-cadillac-ct6-china-1.jpg",
    images: [
      "/Cadillac/2024-cadillac-ct6-china-1.jpg",
      "/Cadillac/2024-cadillac-ct6-china.jpg",
      "/Cadillac/2024-cadillac-ct6-china-3-1000x563.jpg",
      "/Cadillac/2024-cadillac-ct6-china-4 (1).jpg",
      
    ],
    badge: "new",
    trim: "Premium Luxury AWD",
    engine: "2.0L Twin-Turbo V6 (404 hp)",
    transmission: "10-Speed Automatic",
    drivetrain: "AWD",
    seats: 5,
    description: "The 2026 Cadillac CT6 is the pinnacle of American-inspired luxury sedans. Now featuring an industry-leading 33-inch 9K curved display and Magnetic Ride Control 4.0, it offers a seamless blend of sophisticated technology and effortless performance, making it the ultimate choice for those who seek executive-level comfort in a modern fastback design.",
    features: ["33-inch 9K Curved LED Display", "Magnetic Ride Control 4.0", "Super Cruise™ Hands-Free Driving", "AKG Studio 19-Speaker Audio System", "Signature Vertical Matrix LED Lighting", "Nappa Leather Interior with Dark Ash Wood", "20-inch High-Gloss Alloy Wheels"]  
  },
  {
    id: 18,
    name: "Escalade V-Series",
    make: "Cadillac",
    model: "Escalade V-Series",
    year: 2025,
    price: 169000,
    body: "SUV",
    color: "Black Raven",
    mileage: "New",
    mpg: "13 city / 18 hwy",
    image: "/Cadillac/image (11).jpg",
    images: [
      "/Cadillac/image (11).jpg",
      "/Cadillac/image (12).jpg",
      "/Cadillac/image (13).jpg",
      "/Cadillac/image (14).jpg",
    ],
    badge: "V-Series",
    trim: "Sport Platinum",
    engine: "6.2L Supercharged V8 (682 hp)",
    transmission: "10-Speed Automatic",
    drivetrain: "4WD",
    seats: 7,
    description: "The 2025 Cadillac Escalade V-Series is the most powerful SUV ever from Cadillac. Powered by a hand-assembled 6.2L supercharged V8 producing 682 horsepower, this high-performance luxury SUV delivers breathtaking acceleration while maintaining the sophisticated comfort expected from the Escalade lineup.",
    features: ["682 hp Supercharged V8 Engine", "Magnetic Ride Control", "Air Ride Adaptive Suspension", "Super Cruise Hands-Free Driving", "AKG Studio 19-Speaker Audio", "Panoramic LED Display", "Night Vision Technology", "Heavy-Duty Trailering Package"],
  },


  // ── LEXUS ──────────────────────────────────────────────────────────────────
  {
    id: 7,
    name: "Lexus GX 550",
    make: "Lexus",
    model: "GX 500",
    year: 2026,
    price: 82100,
    body: "SUV",
    color: "White",
    mileage: "New",
    mpg: "19 city / 28 hwy",
    image: "/lexus/Screenshot_9-3-2026_638_.jpg",
    images: [
      "/lexus/image (3).jpg",
      "/lexus/image (6).jpg",
      "/lexus/image (4).jpg",
      "/lexus/image (5).jpg",
    ],
    badge: "New Arrival",
    trim: "Lexus GX 550",
    engine: "3.4L Twin-Turbo V6 (349 hp)",
    transmission: "10-Speed Automatic",
    drivetrain: "RWD",
    seats: 7,
    description: "The 2026 Lexus GX 550 Overtrail+ is the ultimate evolution of the legendary off-roader, featuring the striking bi-tone 'Earth' exterior. Built on a high-strength ladder frame and powered by a 349hp twin-turbo V6, it combines extreme capability like E-KDSS and 33-inch tires with world-class Lexus luxury and massaging seats.",  
    features: ["Kiriko Glass Ornaments", "Mark Levinson 23-Speaker Audio", "28-Way Power Front Seats", "Climate Concierge System", "Lexus Safety System+ 3.0", "Touch Tracer Controls", "Shoji Screen Ambient Lighting", "24-inch Triple-Screen Display"],
  },
  {
    id: 8,
    name: "Lexus LC 500",
    make: "Lexus",
    model: "LC 500",
    year: 2026,
    price: 105000,
    body: "Sedan / Coupe",
    color: "Ultrasonic Blue Mica 2.0",
    mileage: "New",
    mpg: "18 Combined",
    image: "/lexus/Lexus-LC-500-Convertible-review-rollers-4.webp",
    images: [
      "/lexus/image (7).jpg",
      "/lexus/image (9).jpg",
      "/lexus/image (10).jpg",
      "/lexus/image (8).jpg",
    ],
    badge: "V8 Performance",
    trim: "Convertible",
    engine: "5.0L Naturally Aspirated V8 - 471 hp",
    transmission: "10-Speed Direct-Shift Automatic",
    drivetrain: "RWD",
    seats: 4,
    description: "The Lexus LC 500 Convertible is a symphony of design and engineering, featuring a legendary 471hp naturally aspirated V8. With its striking Ultrasonic Blue exterior and a roof that opens in just 15 seconds, it offers an unmatched open-air driving experience that blends breathtaking Japanese aesthetics with a spine-tingling exhaust note.",
    features: ["5.0L Naturally Aspirated V8 Engine", "Four-Layer Lightweight Soft Top", "Lexus Safety System+ 2.5", "21-inch Staggered Forged Alloy Wheels", "Mark Levinson 13-Speaker Surround Sound", "Climate Concierge with Upper Body Heating", "Torsen Limited-Slip Differential", "Active Noise Control System"],  },
  {
    id: 9,
    name: "Lexus LX 600 Luxury",
    make: "Lexus",
    model: "LX 600",
    year: 202,
    price: 112100,
    body: "SUV",
    color: "Atomic Silver",
    mileage: "Brand New",
    mpg: "19 Combined",
    image: "/lexus/image (16).jpg",
    images: [
      "/lexus/image (16).jpg",
      "/lexus/image (17).jpg",
      "/lexus/image (18).jpg",
      "/lexus/image (19).jpg",
    ],
    badge: "Flagship",
    trim: "VIP / Ultra Luxury",
    engine: "3.4L Twin-Turbo V6 - 409 hp",
    transmission: "10-Speed Direct-Shift Automatic",
    drivetrain: "4WD",
    seats: 5,
    description: "The Lexus LX 600  stands as the absolute pinnacle of Japanese luxury off-roaders. Featuring a 409hp twin-turbo V6 and an exclusive 4-seat VIP configuration with massaging Ottoman recliners, it provides a private jet experience for the road, whether you are navigating city streets or desert dunes.",
    features: ["Twin-Turbo V6 High-Output Engine", "Executive Rear Seating with Massage", "Active Height Control (AHC) Suspension", "Mark Levinson 25-Speaker Reference Audio", "11.6-inch Dual Rear-Seat Displays", "Multi-Terrain Select with Crawl Control", "Cool Box Storage Area"]
  },

  // ── AUDI ───────────────────────────────────────────────────────────────────
  
{
  id: 10,
  name: "A8 L",
  make: "Audi",
  model: "A8",
  year: 2024,
  price: 800000,
  body: "Sedan",
  color: "District Green Metallic",
  mileage: "New",
  mpg: "19 city / 28 hwy",
  image: "/audi/a8/f.jpg",
  images: [
    "/audi/a8/f.jpg",
    "/audi/a8/s.jpg",
    "/audi/a8/i.jpg",
    "/audi/a8/r.jpg",
  ],
  badge: "Luxury",
  trim: "55 TFSI quattro",
  engine: "3.0L V6 Turbocharged",
  transmission: "8-Speed Tiptronic",
  drivetrain: "quattro (AWD)",
  seats: 5,
  description: "The Audi A8 L stands for a new design language, an innovative operating concept and high-end quality.",
  features: [
    "Valcona Leather Seats",
    "OLED Rear Lights",
    "Bang & Olufsen 3D Sound",
    "Dynamic All-Wheel Steering"
  ]
},
{
  id: 11,
  name: "e-tron GT",
  make: "Audi",
  model: "e-tron GT",
  year: 2024,
  price: 1000000,
  body: "Sedan / Sportback",
  color: "Tactical Green Metallic",
  mileage: "New",
  mpg: "85 MPGe",
  image: "/audi/e/f.jpg",
  images: [
    "/audi/e/f.jpg",
    "/audi/e/s.jpg",
    "/audi/e/i.jpg",
    "/audi/e/r.jpg",
  ],
  badge: "Fully Electric",
  trim: "Premium Plus",
  engine: "Dual Electric Motors (93.4 kWh Battery)",
  transmission: "2-Speed Automatic",
  drivetrain: "quattro (AWD)",
  seats: 5,
  description: "The Audi e-tron GT is a modern take on the grand tourer, offering electrifying performance and sophisticated design.",
  features: [
    "Matrix-design LED Headlights",
    "e-tron Sport Sound",
    "Active Rear Spoiler",
    "Carbon Fiber Inlays"
  ]
},
{
  id: 12,
  name: "Audi Q8",
  make: "Audi",
  model: "Q8",
  year: 2024,
  price: 750000,
  body: "SUV",
  color: "Mythos Black Metallic",
  mileage: "New",
  mpg: "17 city / 23 hwy",
  image: "/audi/q8/f.jpg",
  images: [
    "/audi/q8/f.jpg",
    "/audi/q8/s.jpg",
    "/audi/q8/i.jpg",
    "/audi/q8/r.jpg",
  ],
  badge: "S Line",
  trim: "55 TFSI S Line",
  engine: "3.0L V6 Turbocharged with 48V Hybrid",
  transmission: "8-Speed Tiptronic",
  drivetrain: "quattro (AWD)",
  seats: 5,
  description: "The Audi Q8 combines the elegance of a four-door luxury coupé with the practical versatility of a large SUV.",
  features: [
    "HD Matrix LED Headlights",
    "Virtual Cockpit Plus",
    "Adaptive Air Suspension",
    "Multi-color Ambient Lighting"
  ]
},

  // ── TESLA ──────────────────────────────────────────────────────────────────
  {
    id: 13,
    name: "Model S Plaid",
    make: "Tesla",
    model: "Model S Plaid",
    year: 2024,
    price: 89990,
    body: "Sedan",
    color: "White",
    mileage: "New",
    mpg: "Electric",
    image: "/tesla/modelx/2026-tesla-model-s (4).jpg",
    images: [
      "/tesla/modelx/2026-tesla-model-s (1).jpg",
      "/tesla/modelx/2026-tesla-model-s (3).jpg",
      "/tesla/modelx/2026-tesla-model-s.jpg",
      "/tesla/modelx/2026-tesla-model-s (2).jpg",
      "/tesla/modelx/2026-tesla-model-s (4).jpg",
    ],
    badge: "Electric",
    trim: "Plaid",
    engine: "Tri-Motor Electric — 1,020 hp",
    transmission: "Single-Speed Direct Drive",
    drivetrain: "AWD",
    seats: 5,
    description: "The Tesla Model S Plaid is the fastest production car on the road. With tri-motor all-wheel drive producing 1,020 hp, it completes the quarter mile in 9.23 seconds — making it the quickest accelerating production car ever built.",
    features: ["1,020 hp Tri-Motor", "0–60 mph in Under 2s", "396-Mile Range", "17-inch Cinematic Display", "Full Self-Driving Hardware", "Bioweapon Defence Mode", "Gaming Performance Console", "Autopilot Standard"],
  },
  {
    id: 14,
    name: "Model X",
    make: "Tesla",
    model: "Model X Plaid",
    year: 2025,
    price: 89990,
    body: "SUV",
    color: "white",
    mileage: "New",
    mpg: "Electric",
    image: "/tesla/modelx/2025_tesla_model-x_4dr-suv_plaid_fq_oem_1_1280x855.jpg",
    images: [
      "/tesla/modelx/2025_tesla_model-x_4dr-suv_plaid_fq_oem_1_1280x855.jpg",
      "/tesla/modelx/2025_tesla_model-x_4dr-suv_plaid_i_oem_1_1280x855.avif",
      "/tesla/modelx/2025_tesla_model-x_4dr-suv_plaid_f_oem_2_1280x855.avif",
      "/tesla/modelx/2025_tesla_model-x_4dr-suv_plaid_d_oem_1_1280x855.avif",
      "/tesla/modelx/2025_tesla_model-x_4dr-suv_plaid_rq_oem_4_1280x855.avif",
    ],
    badge: "Electric",
    trim: "Plaid",
    engine: "Tri-Motor Electric — 1,020 hp",
    transmission: "Single-Speed Direct Drive",
    drivetrain: "AWD",
    seats: 7,
    description: "The Tesla Model X Plaid combines a spacious 7-seat interior with supercar performance. Iconic falcon-wing rear doors open effortlessly in tight spaces, while the expansive windshield creates an unrivalled sense of space and light.",
    features: ["Falcon Wing Rear Doors", "1,020 hp Tri-Motor", "Panoramic Windshield", "17-inch Touchscreen", "Autopilot", "360-Mile Range", "HEPA + Bioweapon Defence", "Tow Package (5,000 lb)"],
  },
  {
    id: 15,
    name: "Roadster",
    make: "Tesla",
    model: "Roadster 2025",
    year: 2025,
    price: 250000,
    body: "Coupe",
    color: "Red",
    mileage: "New",
    mpg: "Electric",
    image: "/tesla/modelx/image (32).jpg",
    images: [

      "/tesla/modelx/image (32).jpg",
      "/tesla/modelx/image (33).jpg",
      "/tesla/modelx/image (35).jpg",
      "/tesla/modelx/image (35).jpg",
      "/tesla/modelx/image (34).jpg",
    ],
    badge: "Limited",
    trim: "Founder's Edition",
    engine: "Electric — 0–60 in under 1 second",
    transmission: "Single-Speed Direct Drive",
    drivetrain: "AWD",
    seats: 4,
    description: "The Tesla Roadster is the quickest car ever made. With a claimed sub-1-second 0–60 mph time and a removable glass roof panel, it represents a revolution in what an electric sports car can achieve. Deliveries are strictly limited.",
    features: ["Sub-1-Second 0–60 mph", "250+ mph Top Speed", "Over 600-Mile Range", "Removable Glass Roof", "All-Wheel Drive", "SpaceX Cold-Gas Thruster Package", "Carbon Fibre Body", "Founders Edition Plaque"],
  },

  // ── ROLLS-ROYCE ────────────────────────────────────────────────────────────
  {
    id: 16,
    name: "Phantom",
    make: "Rolls-Royce",
    model: "Phantom",
    year: 2024,
    price: 455000,
    body: "Sedan",
    color: "Black",
    mileage: "New",
    mpg: "14 city / 19 hwy",
    image: "/rolls/image (37).jpg",
    images: [
      "/rolls/image (40).jpg",
      "/rolls/image (41).jpg",
      "/rolls/image (37).jpg",
      "/rolls/image (39).jpg",
    ],
    badge: "Limited",
    trim: "Extended Wheelbase",
    engine: "6.75L Twin-Turbo V12 (563 hp)",
    transmission: "8-Speed Automatic",
    drivetrain: "RWD",
    seats: 4,
    description: "The Rolls-Royce Phantom is the pinnacle of automotive luxury — the greatest car in the world. Hand-assembled at the Home of Rolls-Royce in Goodwood, every Phantom is entirely unique. The Gallery dashboard encases any artefact the owner wishes to display.",
    features: ["Bespoke Gallery Dashboard", "Starlight Headliner (1,340 LEDs)", "Magic Carpet Ride Suspension", "Lambswool Floormats", "Champagne Cooler", "Self-Closing Doors", "Illuminated Spirit of Ecstasy", "Kneeling Function"],
  },
  {
    id: 17,
    name: "Cullinan",
    make: "Rolls-Royce",
    model: "Cullinan",
    year: 2024,
    price: 345000,
    body: "SUV",
    color: "White",
    mileage: "New",
    mpg: "13 city / 20 hwy",
    image: "/rolls/image (45).jpg",
    images: [
      "/rolls/image (46).jpg",
      "/rolls/image (42).jpg",
      "/rolls/image (47).jpg",
      "/rolls/image (44).jpg",
      "/rolls/image (43).jpg",
    ],
    badge: "Limited",
    trim: "Black Badge",
    engine: "6.75L Twin-Turbo V12 (600 hp)",
    transmission: "8-Speed Automatic",
    drivetrain: "AWD",
    seats: 5,
    description: "The Cullinan Black Badge is for those who push boundaries. The Black Badge treatment deepens the Cullinan's character — a darker, more assertive Rolls-Royce that conquers any terrain without surrendering a single ounce of luxury.",
    features: ["Black Badge Darkened Trim", "All-Terrain Capability", "Recreation Module", "Viewing Suite Tailgate Seating", "Panoramic Sunroof", "Self-Closing Doors", "4-Camera Surround View", "Night Vision"],
  },


  // ── ASTON MARTIN ───────────────────────────────────────────────────────────
  {
    id: 19,
    name: "DB12",
    make: "Aston Martin",
    model: "DB12",
    year: 2024,
    price: 245000,
    body: "Coupe",
    color: "Blue",
    mileage: "New",
    mpg: "17 city / 24 hwy",
    image: "/Aston Martin/image (48).jpg",
    images: [
      "/Aston Martin/image (48).jpg",
      "/Aston Martin/image (52).jpg",
      "/Aston Martin/image (49).jpg",
      "/Aston Martin/image (51).jpg",
      "/Aston Martin/image (50).jpg",
    ],
    badge: "New Arrival",
    trim: "Volante",
    engine: "4.0L Twin-Turbo V8 (671 hp)",
    transmission: "8-Speed Automatic",
    drivetrain: "RWD",
    seats: 4,
    description: "The Aston Martin DB12 is the world's first Super Tourer — an entirely new car built to an entirely new standard. With 671 hp and a revised chassis, it combines breathtaking performance with the comfort to cross continents in style.",
    features: ["671 hp Twin-Turbo V8", "0–60 mph in 3.5s", "Bang & Olufsen Audio", "Sports Plus Seats", "Adaptive Damping", "Torque Vectoring Differential", "Panoramic Glass Roof", "Aston Martin Connect"],
  },
  {
    id: 20,
    name: "DBX707",
    make: "Aston Martin",
    model: "DBX707",
    year: 2024,
    price: 239000,
    body: "SUV",
    color: "Synapse Orange",
    mileage: "New",
    mpg: "16 city / 21 hwy",
    image: "/Aston Martin/image (56).jpg",
    images: [
      "/Aston Martin/image (56).jpg",
      "/Aston Martin/image (53).jpg",
      "/Aston Martin/image (55).jpg",
      "/Aston Martin/image (54).jpg",
      
    ],
    badge: "Best Seller",
    trim: "DBX707 AMR24 Edition",
    engine: "4.0L Twin-Turbo V8 AMG (707 hp)",
    transmission: "9-Speed Wet-Clutch Automatic",
    drivetrain: "AWD",
    seats: 5,
    description: "The Aston Martin DBX707 is the world's most powerful luxury SUV. Named after its 707 metric horsepower output, it combines the driving dynamics of a sports car with the practicality of a premium SUV. Inspired by the Formula 1 AMR24.",
    features: ["707 hp Twin-Turbo V8", "Carbon Ceramic Brakes", "22-inch Diamond-Turned Wheels", "Sports Plus Premium Seats", "Meridian Audio System", "Adaptive Damping System", "Electronic Active Rear Differential", "Aerodynamic Carbon Pack"],
  },
  {
    id: 21,
    name: "Vanquish",
    make: "Aston Martin",
    model: "Vanquish",
    year: 2026,
    price: 349000,
    body: "Coupe",
    color: "Caribbean Blue Metallic",
    mileage: "New",
    mpg: "16 city / 23 hwy",
    image: "/Aston Martin/image (57).jpg",
    images: [
      "/Aston Martin/image (57).jpg",
      "/Aston Martin/image (60).jpg",
      "/Aston Martin/image (59).jpg",
      "/Aston Martin/image (58).jpg",
    ],
    badge: "Limited",
    trim: "Vanquish",
    engine: "5.2L Twin-Turbo V12 - 715 hp",
    transmission: "8-Speed Automatic",
    drivetrain: "RWD",
    seats: 4,
    description: "The all-new Aston Martin Vanquish reclaims its position at the pinnacle of Aston Martin's range. With 835 hp from an evolved twin-turbo V8, a bespoke carbon fibre body, and a completely new bonded aluminium architecture, it is Aston Martin's most ambitious car ever.",
    features: ["835 hp Twin-Turbo V8", "Full Carbon Fibre Body", "Bespoke Bonded Aluminium Chassis", "Active Aero System", "Carbon Ceramic Brakes", "Fully Digital Interior", "Sports Bucket Seats", "Track Telemetry System"],
  },

  // ── BENTLEY ────────────────────────────────────────────────────────────────
  {
    id: 22,
    name: "Mulsanne",
    make: "Bentley",
    model: "Mulsanne Speed",
    year: 2023,
    price: 348000,
    body: "Sedan",
    color: "Black",
    mileage: "1,200",
    mpg: "11 city / 17 hwy",
    image: "https://placehold.co/1200x700/0a0a0a/ffffff?text=Bentley+Mulsanne",
    images: [
      "https://placehold.co/1200x700/0a0a0a/ffffff?text=Bentley+Mulsanne",
      "https://placehold.co/1200x700/0a0a0a/ffffff?text=Mulsanne+—+Front",
      "https://placehold.co/1200x700/111111/ffffff?text=Mulsanne+—+Side",
      "https://placehold.co/1200x700/1a1a1a/ffffff?text=Mulsanne+—+Interior",
      "https://placehold.co/1200x700/222222/ffffff?text=Mulsanne+—+Rear",
    ],
    badge: "Limited",
    trim: "Speed",
    engine: "6.75L Twin-Turbo V8 (537 hp)",
    transmission: "8-Speed Automatic",
    drivetrain: "RWD",
    seats: 4,
    description: "The final-year Bentley Mulsanne Speed is an unapologetically opulent collector's piece. Hand-built in Crewe, England, it is trimmed in the finest leathers and veneers available — a monument to traditional British coachbuilding excellence.",
    features: ["Hand-Stitched Leather Throughout", "Burl Walnut Veneers", "Mulliner Driving Specification", "Champagne Cooler", "Individual Rear Picnic Tables", "Naim Audio System", "Four-Zone Climate Control", "Lambswool Overmats"],
  },
  {
    id: 23,
    name: "Flying Spur",
    make: "Bentley",
    model: "Flying Spur",
    year: 2024,
    price: 224000,
    body: "Sedan",
    color: "White",
    mileage: "New",
    mpg: "15 city / 22 hwy",
    image: "/bentley/spur/g.jpg",
    images: [
      "/bentley/spur/g.jpg",
      "/bentley/spur/f.jpg",
      "/bentley/spur/s.jpg",
      "/bentley/spur/i.jpg",
      "/bentley/spur/r.jpg",
    ],
    badge: "New Arrival",
    trim: "W12 S",
    engine: "6.0L W12 TSI (635 hp)",
    transmission: "8-Speed Dual-Clutch",
    drivetrain: "AWD",
    seats: 5,
    description: "The Bentley Flying Spur W12 S redefines luxury performance. With a 635 hp W12 engine and all-wheel drive, it covers the 0–60 mph sprint in 3.7 seconds yet remains utterly composed and cosseting at all speeds.",
    features: ["635 hp W12 Engine", "All-Wheel Steering", "Bentley Rotating Display", "Naim 2,200W Audio", "Diamond-Quilted Leather", "Adaptive Cruise Control", "Night Vision", "Rotating Display Unit"],
  },
  {
    id: 24,
    name: "Bentayga",
    make: "Bentley",
    model: "Bentayga EWB",
    year: 2024,
    price: 233000,
    body: "SUV",
    color: "Gray",
    mileage: "New",
    mpg: "17 city / 23 hwy",
    image: "https://placehold.co/1200x700/0a0a0a/ffffff?text=Bentley+Bentayga",
    images: [
      "https://placehold.co/1200x700/0a0a0a/ffffff?text=Bentley+Bentayga",
      "https://placehold.co/1200x700/0a0a0a/ffffff?text=Bentayga+—+Front",
      "https://placehold.co/1200x700/111111/ffffff?text=Bentayga+—+Side",
      "https://placehold.co/1200x700/1a1a1a/ffffff?text=Bentayga+—+Interior",
      "https://placehold.co/1200x700/222222/ffffff?text=Bentayga+—+Rear",
    ],
    badge: "Best Seller",
    trim: "Extended Wheelbase",
    engine: "4.0L Twin-Turbo V8 (542 hp)",
    transmission: "8-Speed Automatic",
    drivetrain: "AWD",
    seats: 5,
    description: "The Bentley Bentayga Extended Wheelbase redefines first-class travel by SUV. The extended wheelbase creates exceptional rear legroom, while the Airline Seat specification offers reclining rear chairs with massage and leg-rest functions.",
    features: ["Airline Seat Specification", "Massaging Rear Seats", "Naim for Bentley Audio", "Bentley Rear Entertainment", "All-Terrain Specification", "Active Noise Cancellation", "22-inch Wheels", "Tow Bar Preparation"],
  },

  // ── MERCEDES ───────────────────────────────────────────────────────────────
  {
    id: 25,
    name: "Maybach S-Class",
    make: "Mercedes",
    model: "Maybach S 680",
    year: 2024,
    price: 202000,
    body: "Sedan",
    color: "Silver",
    mileage: "New",
    mpg: "14 city / 20 hwy",
    image: "/Mercedes/Mercedes‑Maybach S‑Class/download-free-car-images (5).jpg",
    images: [
      "/Mercedes/Mercedes‑Maybach S‑Class/download-free-car-images (5).jpg",
      "/Mercedes/Mercedes‑Maybach S‑Class/download-free-car-images (1).jpg",
      "/Mercedes/Mercedes‑Maybach S‑Class/download-free-car-images (2).jpg",
      "/Mercedes/Mercedes‑Maybach S‑Class/download-free-car-images (3).jpg",
      "/Mercedes/Mercedes‑Maybach S‑Class/download-free-car-images (4).jpg",
    ],
    badge: "Limited",
    trim: "S 680 4MATIC",
    engine: "6.0L V12 Biturbo (612 hp)",
    transmission: "9-Speed Automatic",
    drivetrain: "AWD",
    seats: 4,
    description: "The Mercedes-Maybach S 680 is the ultimate expression of luxury motoring. Its legendary V12 engine delivers effortless performance while Chauffeur and Owner modes ensure the perfect experience whether you are at the wheel or being driven.",
    features: ["V12 Biturbo Engine", "Rear Executive Seats with Massage", "E-Active Body Control", "Burmester 4D Sound System", "Energising Comfort System", "Heated & Cooled Armrests", "MBUX Rear Entertainment", "Maybach Champagne Flutes"],
  },
  {
    id: 26,
    name: "Maybach GLS",
    make: "Mercedes",
    model: "Maybach GLS 600",
    year: 2024,
    price: 229000,
    body: "SUV",
    color: "Black",
    mileage: "New",
    mpg: "15 city / 20 hwy",
    image: "/Mercedes/Mercedes‑Maybach GLS/download-free-car-images (5).jpg",
    images: [
      "/Mercedes/Mercedes‑Maybach GLS/download-free-car-images (5).jpg",
      "/Mercedes/Mercedes‑Maybach GLS/download-free-car-images (6).jpg",
      "/Mercedes/Mercedes‑Maybach GLS/download-free-car-images (7).jpg",
      "/Mercedes/Mercedes‑Maybach GLS/download-free-car-images (8).jpg",
      "/Mercedes/Mercedes‑Maybach GLS/download-free-car-images (10).jpg",
    ],
    badge: "Limited",
    trim: "GLS 600 4MATIC",
    engine: "4.0L V8 Biturbo EQ Boost (550 hp)",
    transmission: "9-Speed Automatic",
    drivetrain: "AWD",
    seats: 5,
    description: "The Mercedes-Maybach GLS 600 brings limousine-class luxury to the SUV world. An elevated roofline, electronically retractable running boards, and a fully independent air suspension ensure first-class comfort in any environment.",
    features: ["Burmester High-End 3D Audio", "Rear Fridge & Crystal Flutes", "Nappa Leather Throughout", "Heated/Ventilated/Massaging Seats", "MBUX Augmented Reality", "Energising Coach Programme", "E-Active Body Control", "Magic Body Control"],
  },
  {
    id: 27,
    name: "AMG SL",
    make: "Mercedes",
    model: "AMG SL 63",
    year: 2024,
    price: 135000,
    body: "Coupe",
    color: "Red",
    mileage: "New",
    mpg: "17 city / 24 hwy",
    image: "/Mercedes/Mercedes‑AMG SL/download-free-car-images (18).jpg",
    images: [
      "/Mercedes/Mercedes‑AMG SL/download-free-car-images (18).jpg",
      "/Mercedes/Mercedes‑AMG SL/download-free-car-images (19).jpg",
      "/Mercedes/Mercedes‑AMG SL/download-free-car-images (20).jpg",
      "/Mercedes/Mercedes‑AMG SL/download-free-car-images (23).jpg",
      "/Mercedes/Mercedes‑AMG SL/download-free-car-images (22).jpg",
    ],
    badge: "New Arrival",
    trim: "SL 63 4MATIC+",
    engine: "4.0L V8 Biturbo (577 hp)",
    transmission: "9-Speed AMG Speedshift",
    drivetrain: "AWD",
    seats: 4,
    description: "The Mercedes-AMG SL 63 is the iconic roadster reborn with a rear-seat back. Developed entirely by AMG, it rides on a bespoke aluminium space frame and produces 577 hp, while the electrically retractable soft-top deploys in just 15 seconds.",
    features: ["577 hp V8 Biturbo", "Retractable Soft-Top Roof", "AMG Active Ride Control", "AMG Night Package", "Burmester Surround Sound", "Digital Light Headlights", "AMG Dynamic Plus Package", "Nappa Sports Seats"],
  },

  // ── PORSCHE ────────────────────────────────────────────────────────────────
  {
    id: 28,
    name: "Panamera",
    make: "Porsche",
    model: "Panamera Turbo E-Hybrid",
    year: 2024,
    price: 187650,
    body: "Sedan",
    color: "Gray",
    mileage: "New",
    mpg: "22 city / 30 hwy",
    image: "/Porsche/Porsche Panamera/download-free-car-images (11).jpg",
    images: [
      "/Porsche/Porsche Panamera/download-free-car-images (11).jpg",
      "/Porsche/Porsche Panamera/download-free-car-images (16).jpg",
      "/Porsche/Porsche Panamera/download-free-car-images (14).jpg",
      "/Porsche/Porsche Panamera/download-free-car-images (17).jpg",
      "/Porsche/Porsche Panamera/download-free-car-images (15).jpg",
      "/Porsche/Porsche Panamera/download-free-car-images (13).jpg",
    ],
    badge: "New Arrival",
    trim: "Turbo E-Hybrid",
    engine: "4.0L V8 Biturbo + Electric (680 hp combined)",
    transmission: "8-Speed PDK",
    drivetrain: "AWD",
    seats: 5,
    description: "The new Porsche Panamera Turbo E-Hybrid defines the luxury sport saloon. Combining 680 hp from a revised V8 and electric motor, it covers 0–60 mph in 3.2 seconds while shipping a full suite of executive technology and craftsmanship.",
    features: ["680 hp Combined Output", "PDCC Sport Anti-Roll System", "Rear-Axle Steering", "Porsche Active Suspension", "Burmester High-End Audio", "Panoramic Roof System", "Massage Seats Front & Rear", "Night Vision Assist"],
  },
  {
    id: 29,
    name: "Taycan Turbo S",
    make: "Porsche",
    model: "Taycan Turbo S",
    year: 2024,
    price: 190000,
    body: "Sedan",
    color: "White",
    mileage: "New",
    mpg: "Electric",
    image: "/Porsche/Porsche Taycan Turbo S/download-free-car-images (26).jpg",
    images: [
      "/Porsche/Porsche Taycan Turbo S/download-free-car-images (26).jpg",
      "/Porsche/Porsche Taycan Turbo S/download-free-car-images (24).jpg",
      "/Porsche/Porsche Taycan Turbo S/download-free-car-images (25).jpg",
      "/Porsche/Porsche Taycan Turbo S/download-free-car-images (28).jpg",
      "/Porsche/Porsche Taycan Turbo S/download-free-car-images (27).jpg",
    ],
    badge: "Electric",
    trim: "Turbo S",
    engine: "Dual-Motor Electric — 938 hp (Overboost)",
    transmission: "2-Speed PDK",
    drivetrain: "AWD",
    seats: 4,
    description: "The Porsche Taycan Turbo S is the quickest and most powerful Taycan ever made. With 938 hp available in overboost, it sprints from 0–60 mph in 2.4 seconds — while remaining an everyday luxury grand tourer you can drive every single day.",
    features: ["938 hp in Overboost", "0–60 mph in 2.4s", "800V Fast Charging", "Performance Battery Plus", "Carbon Ceramic Composite Brakes", "Porsche Active Suspension", "Sport Chrono Package", "Rear-Axle Steering"],
  },
  {
    id: 30,
    name: "Cayenne Turbo GT",
    make: "Porsche",
    model: "Cayenne Turbo GT",
    year: 2024,
    price: 184650,
    body: "SUV",
    color: "Black",
    mileage: "New",
    mpg: "14 city / 19 hwy",
    image: "/Porsche/Porsche Cayenne Turbo GT/download-free-car-images (29).jpg",
    images: [
      "/Porsche/Porsche Cayenne Turbo GT/download-free-car-images (29).jpg",
      "/Porsche/Porsche Cayenne Turbo GT/download-free-car-images (33).jpg",
      "/Porsche/Porsche Cayenne Turbo GT/download-free-car-images (30).jpg",
      "/Porsche/Porsche Cayenne Turbo GT/download-free-car-images (31).jpg",
      "/Porsche/Porsche Cayenne Turbo GT/download-free-car-images (32).jpg",
    ],
    badge: "Limited",
    trim: "Turbo GT",
    engine: "4.0L Twin-Turbo V8 (659 hp)",
    transmission: "8-Speed Tiptronic S",
    drivetrain: "AWD",
    seats: 5,
    description: "The Porsche Cayenne Turbo GT is the fastest and most powerful Cayenne ever. With 659 hp, a lowered and stiffened chassis, Nürburgring-tuned suspension, and carbon ceramic brakes, it set the SUV lap record at the Nürburgring Nordschleife.",
    features: ["Nürburgring SUV Lap Record", "Carbon Ceramic Brakes", "Torque Vectoring Plus", "GT Sport Steering Wheel", "22-inch GT Design Wheels", "Adaptive Air Suspension", "Sport Exhaust System", "Roll Cage Preparation"],
  },

  // ── GENESIS ────────────────────────────────────────────────────────────────
  {
    id: 31,
    name: "G90",
    make: "Genesis",
    model: "G90",
    year: 2024,
    price: 96500,
    body: "Sedan",
    color: "Metropolitan Gray",
    mileage: "New",
    mpg: "19 city / 27 hwy",
    image: "/genesis/image (67).jpg",
    images: [
      "/genesis/image (61).jpg",
      "/genesis/image (62).jpg",
      "/genesis/image (64).jpg",
      "/genesis/image (66).jpg",
      "/genesis/image (67).jpg",

    ],
    badge: "Premium",
    trim: "Advanced",
    engine: "3.8L Twin-Turbo V6 (409 hp)",
    transmission: "8-Speed Automatic",
    drivetrain: "RWD",
    seats: 5,
    description: "The Genesis G90 represents the pinnacle of automotive elegance and engineering excellence. With a powerful twin-turbo V6, refined interior, and cutting-edge technology, it delivers a premium luxury sedan experience.",
    features: ["409 hp Twin-Turbo V6", "Luxury Leather Interior", "Panoramic Sunroof", "Adaptive Suspension", "Advanced Safety Suite", "Premium Surround Sound", "Power Adjustable Seats", "Wireless Smartphone Charging"],
  },
  {
    id: 32,
    name: "GV80",
    make: "Genesis",
    model: "GV80",
    year: 2024,
    price: 85000,
    body: "SUV",
    color: "Dusk Blue",
    mileage: "New",
    mpg: "18 city / 24 hwy",
    image: "https://placehold.co/1200x700/0a0a0a/ffffff?text=Genesis+GV80",
    images: [
      "https://placehold.co/1200x700/0a0a0a/ffffff?text=Genesis+GV80",
      "https://placehold.co/1200x700/0a0a0a/ffffff?text=GV80+—+Front",
      "https://placehold.co/1200x700/111111/ffffff?text=GV80+—+Side",
      "https://placehold.co/1200x700/1a1a1a/ffffff?text=GV80+—+Interior",
      "https://placehold.co/1200x700/222222/ffffff?text=GV80+—+Rear",
    ],
    badge: "New Arrival",
    trim: "Advanced AWD",
    engine: "3.5L Twin-Turbo V6 (375 hp)",
    transmission: "8-Speed Automatic",
    drivetrain: "AWD",
    seats: 5,
    description: "The Genesis GV80 sets a new standard for luxury SUVs. With its striking crest grille design, powerful twin-turbo engine, and sophisticated interior, it combines premium aesthetics with exceptional performance and comfort.",
    features: ["375 hp Twin-Turbo V6", "All-Wheel Drive", "Premium Leather Seats", "Panoramic Glass Roof", "Dynamic Suspension", "Advanced Driver Assistance", "Luxury Sound System", "Heated & Ventilated Seats"],
  },
  {
    id: 33,
    name: "G80",
    make: "Genesis",
    model: "G80",
    year: 2024,
    price: 65000,
    body: "Sedan",
    color: "Passion Red",
    mileage: "New",
    mpg: "20 city / 28 hwy",
    image: "https://placehold.co/1200x700/0a0a0a/ffffff?text=Genesis+G80",
    images: [
      "https://placehold.co/1200x700/0a0a0a/ffffff?text=Genesis+G80",
      "https://placehold.co/1200x700/0a0a0a/ffffff?text=G80+—+Front",
      "https://placehold.co/1200x700/111111/ffffff?text=G80+—+Side",
      "https://placehold.co/1200x700/1a1a1a/ffffff?text=G80+—+Interior",
      "https://placehold.co/1200x700/222222/ffffff?text=G80+—+Rear",
    ],
    badge: "Best Seller",
    trim: "Prestige AWD",
    engine: "3.5L Twin-Turbo V6 (375 hp)",
    transmission: "8-Speed Automatic",
    drivetrain: "AWD",
    seats: 5,
    description: "The Genesis G80 is a midsize luxury sedan that balances elegant design with robust performance. Its refined interior, advanced technology, and smooth driving dynamics make it an ideal choice for discerning drivers.",
    features: ["375 hp Twin-Turbo V6", "All-Wheel Drive", "Quilted Semi-Aniline Leather", "Panoramic Sunroof", "Adaptive Multi-Chamber Suspension", "Advanced Safety Technology", "Lexicon Premium Audio", "Heated Steering Wheel"],
  },

  // ── LAND ROVER ─────────────────────────────────────────────────────────────
  {
    id: 34,
    name: "Range Rover",
    make: "Land Rover",
    model: "Range Rover",
    year: 2024,
    price: 110000,
    body: "SUV",
    color: "Santorini Black",
    mileage: "New",
    mpg: "16 city / 21 hwy",
    image: "https://placehold.co/1200x700/0a0a0a/ffffff?text=Range+Rover",
    images: [
      "https://placehold.co/1200x700/0a0a0a/ffffff?text=Range+Rover",
      "https://placehold.co/1200x700/0a0a0a/ffffff?text=Range+Rover+—+Front",
      "https://placehold.co/1200x700/111111/ffffff?text=Range+Rover+—+Side",
      "https://placehold.co/1200x700/1a1a1a/ffffff?text=Range+Rover+—+Interior",
      "https://placehold.co/1200x700/222222/ffffff?text=Range+Rover+—+Rear",
    ],
    badge: "Limited",
    trim: "P530 R-Dynamic",
    engine: "4.4L Twin-Turbo V8 (530 hp)",
    transmission: "8-Speed Automatic",
    drivetrain: "All-Wheel Drive",
    seats: 5,
    description: "The Range Rover is the ultimate expression of luxury and capability. With its iconic design, powerful V8 engine, and world-class all-terrain performance, it remains the standard-bearer for premium full-size SUVs.",
    features: ["530 hp Twin-Turbo V8", "Terrain Response 2", "Adaptive Dynamics", "Premium Nappa Leather", "Panoramic Sunroof", "Advanced Meridiuan Audio", "Heated & Massaging Seats", "Configurable Ambient Lighting"],
  },
  {
    id: 35,
    name: "Range Rover SV",
    make: "Land Rover",
    model: "Range Rover SV",
    year: 2024,
    price: 175000,
    body: "SUV",
    color: "Ebony",
    mileage: "New",
    mpg: "16 city / 21 hwy",
    image: "https://placehold.co/1200x700/0a0a0a/ffffff?text=Range+Rover+SV",
    images: [
      "https://placehold.co/1200x700/0a0a0a/ffffff?text=Range+Rover+SV",
      "https://placehold.co/1200x700/0a0a0a/ffffff?text=Range+Rover+SV+—+Front",
      "https://placehold.co/1200x700/111111/ffffff?text=Range+Rover+SV+—+Side",
      "https://placehold.co/1200x700/1a1a1a/ffffff?text=Range+Rover+SV+—+Interior",
      "https://placehold.co/1200x700/222222/ffffff?text=Range+Rover+SV+—+Rear",
    ],
    badge: "Ultra Luxury",
    trim: "SV P530 Bespoke",
    engine: "4.4L Twin-Turbo V8 (530 hp)",
    transmission: "8-Speed Automatic",
    drivetrain: "All-Wheel Drive",
    seats: 5,
    description: "The Range Rover SV represents the ultimate in customization and luxury. Hand-finished by skilled craftsmen, every SV is unique to its owner, featuring bespoke interiors and exclusive personalization options.",
    features: ["530 hp Twin-Turbo V8", "SV Bespoke Customization", "Premium Full Grain Leather", "SV Ebony Veneers", "Executive Class Seating", "Panoramic Glass Roof", "Meridian 3D Audio", "Heated & Cooled Armrests"],
  },
  {
    id: 36,
    name: "Range Rover Sport",
    make: "Land Rover",
    model: "Range Rover Sport",
    year: 2024,
    price: 87500,
    body: "SUV",
    color: "Fuji White",
    mileage: "New",
    mpg: "17 city / 22 hwy",
    image: "https://placehold.co/1200x700/0a0a0a/ffffff?text=Range+Rover+Sport",
    images: [
      "https://placehold.co/1200x700/0a0a0a/ffffff?text=Range+Rover+Sport",
      "https://placehold.co/1200x700/0a0a0a/ffffff?text=Range+Rover+Sport+—+Front",
      "https://placehold.co/1200x700/111111/ffffff?text=Range+Rover+Sport+—+Side",
      "https://placehold.co/1200x700/1a1a1a/ffffff?text=Range+Rover+Sport+—+Interior",
      "https://placehold.co/1200x700/222222/ffffff?text=Range+Rover+Sport+—+Rear",
    ],
    badge: "New Arrival",
    trim: "P440 R-Dynamic",
    engine: "3.0L Twin-Turbo Hybrid (440 hp)",
    transmission: "8-Speed Automatic",
    drivetrain: "All-Wheel Drive",
    seats: 5,
    description: "The Range Rover Sport combines athletic performance with refined luxury. With its advanced hybrid powertrain, responsive handling, and sportscar-inspired design, it offers dynamic driving without compromising on comfort.",
    features: ["440 hp Hybrid Powertrain", "Quick Shift Transmission", "Dynamic Suspension", "Premium Leather Appointments", "Panoramic Roof", "Meridian Surround Sound", "Rear Seat Entertainment", "Hands-Free Gesture Control"],
  },

  // ── FERRARI ────────────────────────────────────────────────────────────────
  {
    id: 37,
    name: "Purosangue",
    make: "Ferrari",
    model: "Purosangue",
    year: 2024,
    price: 390000,
    body: "SUV",
    color: "Rosso Corsa",
    mileage: "New",
    mpg: "11 city / 16 hwy",
    image: "/Ferrari/Ferrari Purosangue/photo1.jpg",
    images: [
      "/Ferrari/Ferrari Purosangue/photo1.jpg",
      "/Ferrari/Ferrari Purosangue/photo2.jpg",
      "/Ferrari/Ferrari Purosangue/photo3.jpg",
      "/Ferrari/Ferrari Purosangue/photo4.jpg",
      "/Ferrari/Ferrari Purosangue/photo5.jpg",
      "/Ferrari/Ferrari Purosangue/photo6.jpg",
      "/Ferrari/Ferrari Purosangue/photo7.jpg",
      "/Ferrari/Ferrari Purosangue/photo8.jpg",
      "/Ferrari/Ferrari Purosangue/photo9.jpg",
      "/Ferrari/Ferrari Purosangue/photo10.jpg",
    ],
    badge: "Exclusive",
    trim: "Base",
    engine: "6.5L Naturally Aspirated V12 (715 hp)",
    transmission: "8-Speed Automatic",
    drivetrain: "All-Wheel Drive",
    seats: 4,
    description: "The Ferrari Purosangue is a game-changing luxury SUV that combines the raw power of a V12 supercar with the practicality of an SUV. With 715 hp, a lightweight carbon fiber body, and Ferrari's legendary handling dynamics, it redefines the high-performance SUV segment.",
    features: ["715 hp V12 Engine", "Carbon Fiber Body", "All-Wheel Drive with Advanced Traction", "Adaptive Suspension", "Premium Leather Interior", "Panoramic Glass Roof", "Brembo High-Performance Brakes", "Advanced Driver Assistance Systems"],
  },
];

// ── Helper: look up a single car by ID ────────────────────────────────────────
export function getCarById(id: number): Car | undefined {
  return allCars.find((c) => c.id === id);
}
